// Output housekeeping: media/ → site/media/ sync and removal of stale generated pages.
import path from 'node:path';
import fsp from 'node:fs/promises';
import { walkFiles, sameFile, copyFilePreserve, removeEmptyDirs, rmrf, joinRel, isFile } from './fsutil.mjs';

export const GENERATED_MARKER = '<!-- generated by tools/build.mjs — 직접 수정하지 마세요 (content/ 수정 후 npm run build) -->';
const MARKER_PROBE = 'generated by tools/build.mjs';

/** Insert the generated-file marker right after the doctype. */
export function addMarker(html) {
  const m = /^\s*<!doctype html>/i.exec(html);
  if (!m) return `<!doctype html>\n${GENERATED_MARKER}\n${html}`;
  return `${html.slice(0, m[0].length)}\n${GENERATED_MARKER}${html.slice(m[0].length)}`;
}

export function hasMarker(html) {
  return String(html).includes(MARKER_PROBE);
}

/**
 * Make siteMediaDir contain exactly `files` (site-relative 'media/...' paths) copied from mediaDir.
 * Copies when size/mtime differ; deletes everything else (consent safety: unpublished media never lingers).
 */
export async function syncMedia({ mediaDir, siteMediaDir, files, dryRun = false }) {
  const wanted = new Set(files.map((f) => f.replace(/^media\//, '')));
  const copied = [];
  const deleted = [];
  const missing = [];
  let unchanged = 0;
  for (const rel of [...wanted].sort()) {
    const src = joinRel(mediaDir, rel);
    const dst = joinRel(siteMediaDir, rel);
    if (!(await isFile(src))) {
      missing.push(rel);
      continue;
    }
    if (await sameFile(src, dst)) {
      unchanged++;
      continue;
    }
    if (!dryRun) await copyFilePreserve(src, dst);
    copied.push(rel);
  }
  for (const rel of await walkFiles(siteMediaDir)) {
    if (wanted.has(rel)) continue;
    if (!dryRun) await fsp.rm(joinRel(siteMediaDir, rel), { force: true });
    deleted.push(rel);
  }
  if (!dryRun) {
    await removeEmptyDirs(siteMediaDir);
    try {
      const left = await fsp.readdir(siteMediaDir);
      if (!left.length) await fsp.rmdir(siteMediaDir);
    } catch {
      /* missing */
    }
  }
  return { copied, deleted, missing, unchanged };
}

/**
 * Delete <outDir>/works/<slug>/ folders that are no longer rendered — only when their index.html carries the
 * generated marker (a hand-made folder is reported, never deleted).
 */
export async function cleanStalePages({ outDir, keepSlugs }) {
  const worksDir = path.join(outDir, 'works');
  const keep = new Set(keepSlugs);
  const removed = [];
  const foreign = [];
  let entries = [];
  try {
    entries = await fsp.readdir(worksDir, { withFileTypes: true });
  } catch {
    return { removed, foreign };
  }
  for (const e of entries) {
    if (!e.isDirectory() || keep.has(e.name)) continue;
    const dir = path.join(worksDir, e.name);
    const index = path.join(dir, 'index.html');
    let generated = false;
    if (await isFile(index)) {
      const html = await fsp.readFile(index, 'utf8').catch(() => '');
      generated = hasMarker(html);
    } else {
      const inside = await walkFiles(dir);
      generated = inside.length === 0; // empty leftover folder
    }
    if (generated) {
      await rmrf(dir);
      removed.push(e.name);
    } else foreign.push(e.name);
  }
  try {
    if (!(await fsp.readdir(worksDir)).length) await fsp.rmdir(worksDir);
  } catch {
    /* ignore */
  }
  return { removed, foreign };
}
