// Output housekeeping: media/ → site/media/ sync and removal of stale generated pages.
import path from 'node:path';
import fsp from 'node:fs/promises';
import { walkFiles, sameFile, copyFilePreserve, removeEmptyDirs, joinRel, isFile } from './fsutil.mjs';

export const GENERATED_MARKER = '<!-- generated by tools/build.mjs — 직접 수정하지 마세요 (content/ 수정 후 npm run build) -->';
const MARKER_PROBE = 'generated by tools/build.mjs';

/** Insert the generated-file marker right after the doctype. */
export function addMarker(html) {
  const m = /^\s*<!doctype html>/i.exec(html);
  if (!m) return `<!doctype html>\n${GENERATED_MARKER}\n${html}`;
  return `${html.slice(0, m[0].length)}\n${GENERATED_MARKER}${html.slice(m[0].length)}`;
}

export function hasMarker(html) {
  return String(html).includes(MARKER_PROBE);
}

/** fs.rm that rides out a short lock (Windows: video player, Explorer preview pane, antivirus, OneDrive). */
async function removeWithRetry(p) {
  await fsp.rm(p, { force: true, recursive: true, maxRetries: 5, retryDelay: 200 });
}

/**
 * Make siteMediaDir contain exactly `files` (site-relative 'media/...' paths) copied from mediaDir.
 * Copies when size/mtime differ; deletes everything else (consent safety: unpublished media never lingers).
 * Deletions run first and never stop half-way: a file that cannot be removed or copied is collected in
 * `failed` ([{ rel, op: 'delete' | 'copy', message }]) and the caller refuses to call the result deployable.
 */
export async function syncMedia({ mediaDir, siteMediaDir, files, dryRun = false }) {
  const wanted = new Set(files.map((f) => f.replace(/^media\//, '')));
  const copied = [];
  const deleted = [];
  const missing = [];
  const failed = [];
  let unchanged = 0;
  for (const rel of await walkFiles(siteMediaDir)) {
    if (wanted.has(rel)) continue;
    if (!dryRun) {
      try {
        await removeWithRetry(joinRel(siteMediaDir, rel));
      } catch (err) {
        failed.push({ rel, op: 'delete', message: err.code || err.message });
        continue;
      }
    }
    deleted.push(rel);
  }
  for (const rel of [...wanted].sort()) {
    const src = joinRel(mediaDir, rel);
    const dst = joinRel(siteMediaDir, rel);
    if (!(await isFile(src))) {
      missing.push(rel);
      continue;
    }
    if (await sameFile(src, dst)) {
      unchanged++;
      continue;
    }
    if (!dryRun) {
      try {
        await copyFilePreserve(src, dst);
      } catch (err) {
        failed.push({ rel, op: 'copy', message: err.code || err.message });
        continue;
      }
    }
    copied.push(rel);
  }
  if (!dryRun) {
    await removeEmptyDirs(siteMediaDir);
    try {
      const left = await fsp.readdir(siteMediaDir);
      if (!left.length) await fsp.rmdir(siteMediaDir);
    } catch {
      /* missing */
    }
  }
  return { copied, deleted, missing, unchanged, failed };
}

/**
 * Delete <outDir>/works/<slug>/ folders that are no longer rendered — only when their index.html carries the
 * generated marker (a hand-made folder is reported, never deleted).
 * hiddenSlugs: slugs of works that must not be public. A hand-made folder with such a name is `blocked` (the
 * build fails) instead of merely `foreign`; a generated one that cannot be deleted is `failed`.
 */
export async function cleanStalePages({ outDir, keepSlugs, hiddenSlugs = [] }) {
  const worksDir = path.join(outDir, 'works');
  const keep = new Set(keepSlugs);
  const hidden = new Set(hiddenSlugs);
  const removed = [];
  const foreign = [];
  const blocked = [];
  const failed = [];
  let entries = [];
  try {
    entries = await fsp.readdir(worksDir, { withFileTypes: true });
  } catch {
    return { removed, foreign, blocked, failed };
  }
  for (const e of entries) {
    if (!e.isDirectory() || keep.has(e.name)) continue;
    const dir = path.join(worksDir, e.name);
    const index = path.join(dir, 'index.html');
    let generated = false;
    if (await isFile(index)) {
      const html = await fsp.readFile(index, 'utf8').catch(() => '');
      generated = hasMarker(html);
    } else {
      const inside = await walkFiles(dir);
      generated = inside.length === 0; // empty leftover folder
    }
    if (generated) {
      try {
        await removeWithRetry(dir);
        removed.push(e.name);
      } catch (err) {
        failed.push({ rel: `works/${e.name}/`, op: 'delete', message: err.code || err.message });
      }
    } else if (hidden.has(e.name)) blocked.push(e.name);
    else foreign.push(e.name);
  }
  try {
    if (!(await fsp.readdir(worksDir)).length) await fsp.rmdir(worksDir);
  } catch {
    /* ignore */
  }
  return { removed, foreign, blocked, failed };
}
